project:
  type: book
  output-dir: docs
  

book:
  title: "MSP"
  author: "Galharret Jean-Michel"
  date: "FÃ©vrier 2026"
  chapters:
    - index.qmd
    - chapitre1.qmd
    - chapitre2.qmd
    - chapitre3.qmd
    - chapitre4.qmd
    - chapitre7.qmd
    - exercice.qmd
    - projet.qmd
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

